name: Generate PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install fonts
        run: |
          sudo apt-get install -y p7zip-full
          wget -c https://github.com/takushun-wu/WenJinMincho/releases/download/v2.001/WenJinMincho-OTC.7z
          wget -c https://software.sil.org/downloads/r/charis/Charis-7.000.zip
          7z x WenJinMincho-OTC.7z -o$HOME/.fonts
          7z x Charis-7.000.zip e Charis-7.000/Charis-Regular.ttf -o$HOME/.fonts
          fc-cache -f -v

      - name: Convert to PDF
        run: |
          python -m pip install md2pdf
          python pdf.py

      - name: Create latest release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: pdf
          prerelease: false
          title: '類音字彙 PDF'
          files: xu.pdf
